import type { Context } from 'hono'
import type { Bindings } from '../type'

type JsonObject = Record<string, unknown>
type AppContext = Context<{ Bindings: Bindings }>

/**リクエストボディとエラーがあればその内容を返す */
export const parseJsonBody = async (c: AppContext) => {
  try {
    // リクエストボディを受け取る
    const body = await c.req.json()
    // !body: nullなどのfalsy値を検知
    // typeof body !== 'object': 文字列・数値・真偽値など、オブジェクト以外を弾く
    // Array.isArray(body): 配列もオブジェクト扱いされるが、JSONオブジェクト以外受け取りたくないので弾く
    if (!body || typeof body !== 'object' || Array.isArray(body)) {
      return { body: null, error: 'JSON object body is required' }
    }
    return { body: body as JsonObject, error: null }
  } catch {
    return { body: null, error: 'Invalid JSON body' }
  }
}

/** UUIDを生成
 * category_で始まるならカテゴリーのUUID
 * bookmarkで始まるならブックマークのUUID
 */
export const generateId = (prefix: 'catrgory' | 'bookmark') => `${prefix}_${crypto.randomUUID()}`

/** nameのバリデーション
 * name系入力の文字列の正規化と入力チェック
 * @returns {{ value: string | null, error: string | null}} value: 正規化後のname文字列 | null, error: エラー内容 | null}
 */
export const normalizeName = (value: unknown, field = 'name') => {
  // valueがstringでないなら弾く
  if (typeof value !== 'string') {
    return { value: null, error: `${field} is required` }
  }

  // valueの前後の空白をtrim()で弾く
  const trimmed = value.trim()
  // 除去後に空文字(falsyな値)なら弾く
  if (!trimmed) {
    return { value: null, error: `${field} is required` }
  }
  // 問題なければエラーなしとして空白除去後の文字列を返す
  return { value: trimmed, error: null }
}

/** sortOrderのバリデーション
 * 任意項目か必須項目かをチェックし、値が正しいか判定
 * @returns {{ value: string | null, error: string | null}} value: 正規化後のsortOrder | null, error: エラー内容 | null
 */
export const normalizeSortOrder = (value: unknown, required: boolean) => {
  // 必須項目でないときに未入力ならOK
  if (value === undefined && !required) {
    return { value: null, error: null }
  }

  // numberかの型チェック & 整数であるかのチェック & 非負数であるかのチェック
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 0) {
    return { value: null, error: 'sortOrder must be a non-negative integer' }
  }
  return { value, error: null }
}

/** URLのバリデーション
 * URL入力の正規化とバリデーション
 * @returns {{ value: string | null, error: string | null}} value: 正規化後のURL | null, error: エラー内容 | null
 */
export const normalizeUrl = (value: unknown) => {
  if (typeof value !== 'string') {
    return { value: null, error: 'url is required' }
  }

  const trimmed = value.trim()
  try {
    const parsed = new URL(trimmed)
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      return { value: null, error: 'url must start with http:// or https://' }
    }
  } catch {
    return { value: null, error: 'url must be a valid URL' }
  }

  return { value: trimmed, error: null }
}

/** クライアントでのID指定拒否 */
export const rejectClientId = (body: JsonObject) => {
  if ('id' in body) {
    return 'id is generated by API and cannot be specified'
  }
  return null
}
